// Drift guard — sdk-claim's INLINED Merkle verifier (merkle-internal.ts)
// must stay byte-for-byte in lockstep with @foxbook/core.
//
// merkle-internal.ts is a hand-maintained copy of core's verifyInclusion
// (+ its reconstructFromPath / interiorHash / largestPow2LessThan
// helpers) because @foxbook/core is a private workspace package that
// won't ship to npm — so the SDK can't depend on it at runtime. The cost
// of that inlining is drift risk: if core's tree math changes and the
// inlined copy isn't updated, the two silently diverge and downstream
// verifiers reject proofs the log considers valid.
//
// This test pins the inlined copy against schemas/merkle-test-vectors.json
// — the SAME cross-language ground truth core asserts against
// (core/__tests__/merkle.test.ts) and the Python verifier consumes. The
// vectors are GENERATED by core's impl (see the file's $comment), so if
// every committed vector verifies through the inlined verifyInclusion,
// the inlined copy is in parity with core for the entire vector surface.

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { sha256 } from "@noble/hashes/sha2.js";
import { describe, expect, it } from "vitest";

import { verifyInclusion } from "../src/merkle-internal.js";

const LEAF_PREFIX = 0x00;

/** SHA-256(0x00 || preimage) — RFC 9162 §2.1 leaf hash. Re-derived here
 *  (not imported from core) so the test independently reconstructs the
 *  leaf hashes the vectors were generated from. */
function leafHash(preimage: Uint8Array): Uint8Array {
  const buf = new Uint8Array(1 + preimage.length);
  buf[0] = LEAF_PREFIX;
  buf.set(preimage, 1);
  return sha256(buf);
}

function bytes(s: string): Uint8Array {
  return new TextEncoder().encode(s);
}

function fromHex(s: string): Uint8Array {
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) out[i] = Number.parseInt(s.slice(i * 2, i * 2 + 2), 16);
  return out;
}

type MerkleVectors = {
  empty_tree_root_hex: string;
  inclusion: Array<{
    leaves: string[];
    leaf_index: number;
    proof_hex: string[];
    root_hex: string;
  }>;
};

// schemas/ lives at the repo root, four levels up from this test file
// (packages/sdk-claim/__tests__/). Loaded via readFileSync so the large
// fixture stays out of the published package's TS graph.
const VECTORS_PATH = fileURLToPath(
  new URL("../../../schemas/merkle-test-vectors.json", import.meta.url),
);
const vectors = JSON.parse(readFileSync(VECTORS_PATH, "utf8")) as MerkleVectors;

describe("merkle-internal drift guard — parity with @foxbook/core vectors", () => {
  it("has inclusion vectors to assert against", () => {
    expect(vectors.inclusion.length).toBeGreaterThan(0);
  });

  it("every committed inclusion vector verifies through the inlined verifyInclusion", () => {
    for (const v of vectors.inclusion) {
      const leaves = v.leaves.map((s) => bytes(s));
      const proof = v.proof_hex.map((h) => fromHex(h));
      const lh = leafHash(leaves[v.leaf_index]!);
      const root = fromHex(v.root_hex);
      // The inlined copy MUST accept every proof core generated. A
      // divergence here means merkle-internal.ts drifted from core.
      expect(verifyInclusion(proof, v.leaf_index, lh, leaves.length, root)).toBe(true);
    }
  });

  it("rejects a tampered leaf hash for every vector (no false positives)", () => {
    for (const v of vectors.inclusion) {
      const leaves = v.leaves.map((s) => bytes(s));
      const proof = v.proof_hex.map((h) => fromHex(h));
      const root = fromHex(v.root_hex);
      const tampered = new Uint8Array(leafHash(leaves[v.leaf_index]!));
      tampered[0] ^= 0x01;
      expect(verifyInclusion(proof, v.leaf_index, tampered, leaves.length, root)).toBe(false);
    }
  });

  it("rejects a tampered root for every vector", () => {
    for (const v of vectors.inclusion) {
      const leaves = v.leaves.map((s) => bytes(s));
      const proof = v.proof_hex.map((h) => fromHex(h));
      const lh = leafHash(leaves[v.leaf_index]!);
      const root = new Uint8Array(fromHex(v.root_hex));
      root[0] ^= 0x01;
      expect(verifyInclusion(proof, v.leaf_index, lh, leaves.length, root)).toBe(false);
    }
  });
});
